### ISSUE TITLE
question for help

### ISSUE THREAD

**Issue by ghost** [Taming-the-BEAST/Taming-the-BEAST.github.io#1]
@tgvaughan When I run the command "bundle exec jekyll build", and it reported that:
Liquid Exception: Liquid error: Cannot sort a null object. in tutorials/professional/index.html.
Could you please help me figure it out, thanks.:)

**Comment by tgvaughan** [comment]
Hi @lixingguang, this is repository does not contain the source: for that, use https://github.com/Taming-the-BEAST/blotter.
